name: "Deploy AWS with Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7
          terraform_wrapper: false

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Setup SSH Public Key
        run: echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/anhtaihtkey.pub

      - name: Check and Delete Existing Key Pair
        run: |
          if aws ec2 describe-key-pairs --key-names "anhtaihtkey" > /dev/null 2>&1; then
            echo "Key Pair already exists. Deleting it."
            aws ec2 delete-key-pair --key-name "anhtaihtkey"
          fi

      - name: Terraform format
        id: fmt
        run: terraform fmt -recursive
      
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
    